/*
 * QuakeSaver Frontend API
 *
 * This implements an API for the Frontend to communicate with the Backend.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FrontendSettings : information about frontend visualization.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FrontendSettings {
    #[serde(rename = "language", skip_serializing_if = "Option::is_none")]
    pub language: Option<models::SupportedFrontendLanguages>,
    #[serde(rename = "colors", skip_serializing_if = "Option::is_none")]
    pub colors: Option<models::SupportedFrontendColorThemes>,
    #[serde(rename = "unit_system", skip_serializing_if = "Option::is_none")]
    pub unit_system: Option<models::SupportedFrontendUnitSystem>,
    #[serde(rename = "branding", skip_serializing_if = "Option::is_none")]
    pub branding: Option<String>,
}

impl FrontendSettings {
    /// information about frontend visualization.
    pub fn new() -> FrontendSettings {
        FrontendSettings {
            language: None,
            colors: None,
            unit_system: None,
            branding: None,
        }
    }
}

