/*
 * QuakeSaver Frontend API
 *
 * This implements an API for the Frontend to communicate with the Backend.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GroupCreate : A class to reflect a permission group.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GroupCreate {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "comment")]
    pub comment: String,
    #[serde(rename = "color")]
    pub color: String,
    #[serde(rename = "influxdb_connection", skip_serializing_if = "Option::is_none")]
    pub influxdb_connection: Option<Box<models::InfluxDbConnectionCreate>>,
}

impl GroupCreate {
    /// A class to reflect a permission group.
    pub fn new(name: String, comment: String, color: String) -> GroupCreate {
        GroupCreate {
            name,
            comment,
            color,
            influxdb_connection: None,
        }
    }
}

