/*
 * QuakeSaver Frontend API
 *
 * This implements an API for the Frontend to communicate with the Backend.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Group : A class to reflect a permission group.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Group {
    #[serde(rename = "uid")]
    pub uid: String,
    #[serde(rename = "owner_uid")]
    pub owner_uid: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "comment")]
    pub comment: String,
    #[serde(rename = "is_active")]
    pub is_active: bool,
    #[serde(rename = "influxdb_connection", skip_serializing_if = "Option::is_none")]
    pub influxdb_connection: Option<Box<models::InfluxDbConnection>>,
    #[serde(rename = "color")]
    pub color: String,
}

impl Group {
    /// A class to reflect a permission group.
    pub fn new(uid: String, owner_uid: String, name: String, comment: String, is_active: bool, color: String) -> Group {
        Group {
            uid,
            owner_uid,
            name,
            comment,
            is_active,
            influxdb_connection: None,
            color,
        }
    }
}

