/*
 * QuakeSaver Frontend API
 *
 * This implements an API for the Frontend to communicate with the Backend.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Permission : A class to reflect permissions of a subject on an object.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Permission {
    #[serde(rename = "groups")]
    pub groups: std::collections::HashMap<String, models::PermissionLevel>,
    #[serde(rename = "primary_group", skip_serializing_if = "Option::is_none")]
    pub primary_group: Option<String>,
}

impl Permission {
    /// A class to reflect permissions of a subject on an object.
    pub fn new(groups: std::collections::HashMap<String, models::PermissionLevel>) -> Permission {
        Permission {
            groups,
            primary_group: None,
        }
    }
}

