/*
 * QuakeSaver Frontend API
 *
 * This implements an API for the Frontend to communicate with the Backend.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_repr::{Serialize_repr,Deserialize_repr};
/// PermissionLevel : An enum to reflect the possible access level.
/// An enum to reflect the possible access level.
#[repr(i64)]
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr)]
pub enum PermissionLevel {
    Variant1 = 1,
    Variant2 = 2,
    Variant4 = 4,

}

impl std::fmt::Display for PermissionLevel {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", match self {
            Self::Variant1 => "1",
            Self::Variant2 => "2",
            Self::Variant4 => "4",
        })
    }
}
impl Default for PermissionLevel {
    fn default() -> PermissionLevel {
        Self::Variant1
    }
}

