/*
 * QuakeSaver Frontend API
 *
 * This implements an API for the Frontend to communicate with the Backend.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SensorWarnings : warnings for the sensor.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SensorWarnings {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<std::collections::HashMap<String, models::SensorWarning>>,
}

impl SensorWarnings {
    /// warnings for the sensor.
    pub fn new() -> SensorWarnings {
        SensorWarnings {
            data: None,
        }
    }
}

