/*
 * QuakeSaver Frontend API
 *
 * This implements an API for the Frontend to communicate with the Backend.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SensorGroupAdd : A schema for adding a group to a sensor.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SensorGroupAdd {
    #[serde(rename = "permission_level")]
    pub permission_level: models::PermissionLevel,
    #[serde(rename = "group_uid")]
    pub group_uid: String,
}

impl SensorGroupAdd {
    /// A schema for adding a group to a sensor.
    pub fn new(permission_level: models::PermissionLevel, group_uid: String) -> SensorGroupAdd {
        SensorGroupAdd {
            permission_level,
            group_uid,
        }
    }
}

