/*
 * QuakeSaver Frontend API
 *
 * This implements an API for the Frontend to communicate with the Backend.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SensorGroupUpdate : A schema for updating a group of a sensor.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SensorGroupUpdate {
    #[serde(rename = "permission_level")]
    pub permission_level: models::PermissionLevel,
}

impl SensorGroupUpdate {
    /// A schema for updating a group of a sensor.
    pub fn new(permission_level: models::PermissionLevel) -> SensorGroupUpdate {
        SensorGroupUpdate {
            permission_level,
        }
    }
}

