/*
 * QuakeSaver Frontend API
 *
 * This implements an API for the Frontend to communicate with the Backend.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SupportedFrontendLanguages : List of languages that can be used in the frontend.  Codes are ISO 639-2/T. See https://en.wikipedia.org/wiki/ISO_639 for more information.
/// List of languages that can be used in the frontend.  Codes are ISO 639-2/T. See https://en.wikipedia.org/wiki/ISO_639 for more information.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SupportedFrontendLanguages {
    #[serde(rename = "eng")]
    Eng,
    #[serde(rename = "deu")]
    Deu,
    #[serde(rename = "zho")]
    Zho,
    #[serde(rename = "jpn")]
    Jpn,

}

impl std::fmt::Display for SupportedFrontendLanguages {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Eng => write!(f, "eng"),
            Self::Deu => write!(f, "deu"),
            Self::Zho => write!(f, "zho"),
            Self::Jpn => write!(f, "jpn"),
        }
    }
}

impl Default for SupportedFrontendLanguages {
    fn default() -> SupportedFrontendLanguages {
        Self::Eng
    }
}

