/*
 * QuakeSaver Frontend API
 *
 * This implements an API for the Frontend to communicate with the Backend.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SupportedFrontendUnitSystem : Physical units schemes, that can be used in the frontend.
/// Physical units schemes, that can be used in the frontend.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SupportedFrontendUnitSystem {
    #[serde(rename = "imperial")]
    Imperial,
    #[serde(rename = "metric")]
    Metric,

}

impl std::fmt::Display for SupportedFrontendUnitSystem {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Imperial => write!(f, "imperial"),
            Self::Metric => write!(f, "metric"),
        }
    }
}

impl Default for SupportedFrontendUnitSystem {
    fn default() -> SupportedFrontendUnitSystem {
        Self::Imperial
    }
}

