/*
 * QuakeSaver Frontend API
 *
 * This implements an API for the Frontend to communicate with the Backend.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserMail : A schema for actions that only require the users mail.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserMail {
    #[serde(rename = "email")]
    pub email: String,
}

impl UserMail {
    /// A schema for actions that only require the users mail.
    pub fn new(email: String) -> UserMail {
        UserMail {
            email,
        }
    }
}

