/*
 * QuakeSaver Frontend API
 *
 * This implements an API for the Frontend to communicate with the Backend.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserSuperuserUpdate : A schema with information a user can be updated by a superuser.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserSuperuserUpdate {
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "frontend_setting", skip_serializing_if = "Option::is_none")]
    pub frontend_setting: Option<Box<models::FrontendSettingsUpdate>>,
    #[serde(rename = "seedlink_ipv4_networks", skip_serializing_if = "Option::is_none")]
    pub seedlink_ipv4_networks: Option<Vec<String>>,
    #[serde(rename = "is_active", skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
    #[serde(rename = "is_verified", skip_serializing_if = "Option::is_none")]
    pub is_verified: Option<bool>,
    #[serde(rename = "rabbitmq_tags", skip_serializing_if = "Option::is_none")]
    pub rabbitmq_tags: Option<Vec<String>>,
    #[serde(rename = "rabbitmq_vhosts", skip_serializing_if = "Option::is_none")]
    pub rabbitmq_vhosts: Option<Vec<String>>,
    #[serde(rename = "groups", skip_serializing_if = "Option::is_none")]
    pub groups: Option<Vec<String>>,
    #[serde(rename = "primary_group", skip_serializing_if = "Option::is_none")]
    pub primary_group: Option<String>,
}

impl UserSuperuserUpdate {
    /// A schema with information a user can be updated by a superuser.
    pub fn new() -> UserSuperuserUpdate {
        UserSuperuserUpdate {
            email: None,
            password: None,
            name: None,
            frontend_setting: None,
            seedlink_ipv4_networks: None,
            is_active: None,
            is_verified: None,
            rabbitmq_tags: None,
            rabbitmq_vhosts: None,
            groups: None,
            primary_group: None,
        }
    }
}

