/*
 * QuakeSaver Frontend API
 *
 * This implements an API for the Frontend to communicate with the Backend.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserAuthenticate : A schema for authenticating a user via the database service.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserAuthenticate {
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "password")]
    pub password: String,
}

impl UserAuthenticate {
    /// A schema for authenticating a user via the database service.
    pub fn new(email: String, password: String) -> UserAuthenticate {
        UserAuthenticate {
            email,
            password,
        }
    }
}

