/*
 * QuakeSaver Frontend API
 *
 * This implements an API for the Frontend to communicate with the Backend.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserCreate : A schema for user creation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserCreate {
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "password")]
    pub password: String,
    #[serde(rename = "frontend_settings", skip_serializing_if = "Option::is_none")]
    pub frontend_settings: Option<Box<models::FrontendSettings>>,
}

impl UserCreate {
    /// A schema for user creation.
    pub fn new(username: String, email: String, name: String, password: String) -> UserCreate {
        UserCreate {
            username,
            email,
            name,
            password,
            frontend_settings: None,
        }
    }
}

