name: Deploy

on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:

  binary-x86:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --release
      - name: upload artefact
        uses: actions/upload-artifact@v4
        with:
          pattern: sqcli
          path: target/release/sqcli
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/release/sqcli

  debian-package:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install cargo-deb
        run: cargo install cargo-deb
      - name: Build
        run: cargo deb
      - name: Rename artifact
        run: cp target/debian/sqcli_*.deb target/debian/sqcli-${{ github.ref_name }}.deb
      - name: upload artefact
        uses: actions/upload-artifact@v4
        with:
          name: sqcli-${{ github.ref_name }}.deb
          path: target/debian/sqcli-${{ github.ref_name }}.deb
          merge-multiple: true
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/debian/sqcli-*.deb

  release-windows:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - name: Build Release
        run: cargo build --release
      - name: Rename artifact
        run: ls target/release/

      - name: upload artefact
        uses: actions/upload-artifact@v4
        with:
          name: sqcli.exe
          path: target/release/sqcli.exe
          merge-multiple: true

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/release/sqcli.exe

  release-osx:
    runs-on: macos-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v2
    - name: Build Release
      run: cargo build --release
    - name: Rename artifact
      run: cp target/release/sqcli target/release/sqcli-osx

    - name: upload artefact
      uses: actions/upload-artifact@v4
      with:
        name: sqcli-osx
        path: target/release/sqcli-osx
        merge-multiple: true

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: target/release/sqcli-osx
